### ISSUE TITLE
Missing files wanted

### ISSUE THREAD

**Issue by Zero-Blue** [ZanderChang/rlfuzz#1]
It seems that there are missing files in the "lava-m-mod" directory?Could you please upload all of the files needed in the source code?Thanks :)

**Comment by ZanderChang** [comment]
Do you mean the source code of LAVA ? It should be downloaded by `wget` from internet and the whole process is implemented in [`Makefile`](https://github.com/ZanderChang/rlfuzz/blob/master/rlfuzz/mods/Makefile#L24) when installing with `pip install .`.

**Comment by Zero-Blue** [comment]
发现是国人..请问怎么下载您在IMIS上的那篇paper呢..方便的话可以留个联系方式交流一下吗：>

**Comment by ZanderChang** [comment]
我的邮箱是zhangzheng232@hotmail.com，论文的话可以到scihub找找😂找不到的话邮箱联系我
